//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioteczkaService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ksiazka", Namespace="http://schemas.datacontract.org/2004/07/BiblioteczkaWCF.Models")]
    public partial class Ksiazka : object
    {
        
        private string AutorField;
        
        private int IDField;
        
        private int IloscStronField;
        
        private string TytulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autor
        {
            get
            {
                return this.AutorField;
            }
            set
            {
                this.AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IloscStron
        {
            get
            {
                return this.IloscStronField;
            }
            set
            {
                this.IloscStronField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul
        {
            get
            {
                return this.TytulField;
            }
            set
            {
                this.TytulField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BiblioteczkaService.IKontekstBiblioteczki")]
    public interface IKontekstBiblioteczki
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontekstBiblioteczki/Dodaj", ReplyAction="http://tempuri.org/IKontekstBiblioteczki/DodajResponse")]
        System.Threading.Tasks.Task DodajAsync(string tytul, string autor, int iloscStron);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontekstBiblioteczki/Edytuj", ReplyAction="http://tempuri.org/IKontekstBiblioteczki/EdytujResponse")]
        System.Threading.Tasks.Task EdytujAsync(int id, string tytul, string autor, int iloscStron);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontekstBiblioteczki/Usun", ReplyAction="http://tempuri.org/IKontekstBiblioteczki/UsunResponse")]
        System.Threading.Tasks.Task UsunAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontekstBiblioteczki/Pobierz", ReplyAction="http://tempuri.org/IKontekstBiblioteczki/PobierzResponse")]
        System.Threading.Tasks.Task<BiblioteczkaService.Ksiazka> PobierzAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKontekstBiblioteczki/PobierzWszystkie", ReplyAction="http://tempuri.org/IKontekstBiblioteczki/PobierzWszystkieResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<BiblioteczkaService.Ksiazka>> PobierzWszystkieAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IKontekstBiblioteczkiChannel : BiblioteczkaService.IKontekstBiblioteczki, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class KontekstBiblioteczkiClient : System.ServiceModel.ClientBase<BiblioteczkaService.IKontekstBiblioteczki>, BiblioteczkaService.IKontekstBiblioteczki
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KontekstBiblioteczkiClient() : 
                base(KontekstBiblioteczkiClient.GetDefaultBinding(), KontekstBiblioteczkiClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IKontekstBiblioteczki.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KontekstBiblioteczkiClient(EndpointConfiguration endpointConfiguration) : 
                base(KontekstBiblioteczkiClient.GetBindingForEndpoint(endpointConfiguration), KontekstBiblioteczkiClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KontekstBiblioteczkiClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KontekstBiblioteczkiClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KontekstBiblioteczkiClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KontekstBiblioteczkiClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KontekstBiblioteczkiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task DodajAsync(string tytul, string autor, int iloscStron)
        {
            return base.Channel.DodajAsync(tytul, autor, iloscStron);
        }
        
        public System.Threading.Tasks.Task EdytujAsync(int id, string tytul, string autor, int iloscStron)
        {
            return base.Channel.EdytujAsync(id, tytul, autor, iloscStron);
        }
        
        public System.Threading.Tasks.Task UsunAsync(int id)
        {
            return base.Channel.UsunAsync(id);
        }
        
        public System.Threading.Tasks.Task<BiblioteczkaService.Ksiazka> PobierzAsync(int id)
        {
            return base.Channel.PobierzAsync(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<BiblioteczkaService.Ksiazka>> PobierzWszystkieAsync()
        {
            return base.Channel.PobierzWszystkieAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKontekstBiblioteczki))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IKontekstBiblioteczki))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:56764/Biblioteczka.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return KontekstBiblioteczkiClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IKontekstBiblioteczki);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return KontekstBiblioteczkiClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IKontekstBiblioteczki);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IKontekstBiblioteczki,
        }
    }
}
